root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
cmd = "go generate && go build -o tmp/main ."
bin = "tmp/main --env=dev"
delay = 1000
exclude_dir = ["tmp", "vendor", "testdata", "docs"]
exclude_file = []
exclude_regex = ["_test.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[proxy]
enabled = true
proxy_port = 8090
app_port = 3000

[screen]
clear_on_rebuild = true
keep_scroll = true
